### ISSUE TITLE
Where is network.yolo

### ISSUE THREAD

**Issue by JunShao-Hub** [AceCoooool/YOLO-Pytorch#1]
Excuse me, where is yolo.weights, thank you!

Traceback (most recent call last):
  File "tools/yad2t.py", line 13, in <module>
    from network.yolo import yolo
ImportError: No module named network.yolo

**Comment by AceCoooool** [comment]
1. You can download the weights and cfg from [offical website](https://pjreddie.com/darknet/yolo/) 
2. Due to the line of `sys.path.append('..')`: You should run it under the directory of tools (You can delete this line if you run in IDE---like Pycharm)

**Comment by ipshita2396** [comment]
Can't seem to resolve this issue still!  
File "yad2t.py", line 12, in <module>
    from network.yolo import yolo
ModuleNotFoundError: No module named 'network.yolo'; 'network' is not a package

**Comment by Srking501** [comment]
It seems to work when you add the following on top of the `yad2t.py` under `tools/` directory.

```python
current_dir = os.path.dirname(os.path.realpath(__file__))
to_network = os.path.join(current_dir, '..')

sys.path.append(to_network)
from network.yolo import yolo
```
