### ISSUE TITLE
将.weight的参数导成.pth文件出错

### ISSUE THREAD

**Issue by georgeokelly** [AceCoooool/YOLO-Pytorch#2]
你好，我从官网下载的yolo2-tiny.cfg和yolo2-tiny.weights，然后导成.pth文件出错

```
Weights Header:  [       0        2        0 26316800]
loading the weights ...
conv2d bn leaky (16, 3, 3, 3)
Traceback (most recent call last):
  File "yad2t.py", line 126, in <module>
    weight2pth(config.cfg_path, config.weight_path, config.output_path)
  File "yad2t.py", line 84, in weight2pth
    net_dict[keys[key_num + 1]].copy_(torch.from_numpy(bn_weights[0]))
RuntimeError: inconsistent tensor size, expected tensor [32] and src [16] to have the same number of elements, but got 32 and 16 elements respectively at /opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/TH/generic/THTensorCopy.c:86

```

这应该怎么解决？谢谢

**Comment by AceCoooool** [comment]
这部分主要由于官方的参数已经更新了（以前的没了～,个人写的几个对应文件是按照以前的来实现），至于yolo-voc的参数以及yolo3的参数可以参考个人的另一个实现提供的几个云盘里面[detection](https://github.com/AceCoooool/detection-pytorch)。（如有必要，我明天再用另一台电脑将之前的参数上传一份～）

**Comment by georgeokelly** [comment]
那麻烦您上传一份，万分感谢~

**Comment by AceCoooool** [comment]
[yolo-weights](https://pan.baidu.com/s/1oZDP_4BrCJIGBhfo7xZOGg)：我也试了下转换，针对tiny-yolo.weights确实存在问题（后续我再找找哪里出问题）～ 其他三个模型：yolo, yolo-voc和tiny-yolo-voc是没问题的～（当然，更欢迎使用个人最近更新的新的版本 :joy: ）
