### ISSUE TITLE
weights 转 pth 报错

### ISSUE THREAD

**Issue by yluo39github** [AceCoooool/YOLO-Pytorch#4]
Weights Header:  [       0        1        0 32013312]
loading the weights ...
conv2d bn leaky (32, 3, 3, 3)
conv2d bn leaky (64, 32, 3, 3)
Traceback (most recent call last):
  File "tools/yad2t.py", line 124, in <module>
    weight2pth(config.cfg_path, config.weight_path, config.output_path)
  File "tools/yad2t.py", line 84, in weight2pth
    net_dict[keys[key_num + 1]].copy_(torch.from_numpy(bn_weights[0]))
RuntimeError: The size of tensor a (3) must match the size of tensor b (64) at non-singleton dimension 3

**Comment by dorianboille** [comment]
Same problem
