### ISSUE TITLE
Can't get yad2t.py to function

### ISSUE THREAD

**Issue by robhammett** [AceCoooool/YOLO-Pytorch#5]
command ran:
python3 tools/yad2t.py --cfg_path config/yolov4-custom.cfg --weight_path config/yolov4-custom_best.weights --output_path config/model

results from command:
Weights Header:  [     0      2      5 320000]
Traceback (most recent call last):
  File "tools/yad2t.py", line 124, in <module>
  weight2pth(config.cfg_path, config.weight_path, config.output_path)
 File "tools/yad2t.py", line 48, in weight2pth
 cfg = importlib.import_module('config.' + cfgname)
 File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
 return _bootstrap._gcd_import(name[level:], package, level)
 File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config.yolov4-custom'

Any idea how to get this to function?

**Comment by RuochenQi** [comment]
same problem: 
  File "yad2t.py", line 48, in weight2pth
    cfg = importlib.import_module('config.' + cfgname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config.yolo-obj'

Did you solve it?

**Comment by dorianboille** [comment]
Your files need to be yolo.cfg and yolo.weights (or tiny-yolo.cfg and tiny-yolo.weights)
